# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.cache/wt [current_project]
set_property parent.project_path /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.board [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths {
  /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.ipdefs/project_ips_0_0
  /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.ipdefs/vivado-library-master_0_0
} [current_project]
set_property ip_output_repo /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_intc_0_0/design_1_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_intc_0_0/design_1_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_intc_0_0/design_1_axi_intc_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_ila_2_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_ila_2_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_ila_2_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_ila_2_0/design_1_ila_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_PmodMAXSONAR_0_0/src/PmodMAXSONAR_pmod_bridge_0_0/PmodMAXSONAR_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_PmodMAXSONAR_0_0/src/PmodMAXSONAR_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_PmodMAXSONAR_0_0/design_1_PmodMAXSONAR_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_PmodMAXSONAR_0_0/src/PmodMAXSONAR_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_PmodMAXSONAR_1_1/src/PmodMAXSONAR_pmod_bridge_0_0/PmodMAXSONAR_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_PmodMAXSONAR_1_1/src/PmodMAXSONAR_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_PmodMAXSONAR_1_1/design_1_PmodMAXSONAR_1_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_PmodMAXSONAR_1_1/src/PmodMAXSONAR_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_video_in_ip_0_1/src/v_vid_in_axi4s_0/v_vid_in_axi4s_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_div_gen_0_3/design_1_div_gen_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files /home/fyyaz/ece532/light_detector_system_final_final/light_detector_system.srcs/constrs_1/new/constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
